name: 🧩 Task
description: Q-IT 개발, 테스트, 문서화 등 일반 작업을 기록합니다.
title: "[Task]: "
labels: [task]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        ## 🧱 작업 작성 가이드
        제목은 아래 형식으로 입력해주세요:
        - `[Task]: 질문 추천 API 문서화`
        - `[Task]: 배포 파이프라인 환경 변수 정리`

  - type: textarea
    id: details
    attributes:
      label: 작업 내용
      placeholder: ex) Spring REST Docs를 적용하여 /api/questions/recommend 엔드포인트 문서화
    validations:
      required: true

  - type: dropdown
    id: type
    attributes:
      label: 작업 유형
      options:
        - 🧱 개발
        - 🧪 테스트
        - 📄 문서화
        - 🔧 리팩토링
        - 🚀 배포

  - type: dropdown
    id: priority
    attributes:
      label: 우선순위
      options:
        - 🔥 High
        - ⚡ Medium
        - 🧊 Low

  - type: input
    id: due_date
    attributes:
      label: 예상 완료일
      placeholder: ex) 2025-10-25
